
-- comparing the major values by categories
-- helps us to understand the importance of different categories

-- find total customers by countries
select
country,
COUNT(customer_key) as total_customers
from gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- find total customers by gender
select
gender,
COUNT(customer_key) as total_customers
from gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- find total products by category
select
product_cat,
COUNT(product_key) as total_products
from gold.dim_products
GROUP BY product_cat
ORDER BY total_products DESC

-- what is the avg cost in each category ?
select
product_cat,
AVG(product_cost) as avg_cost
from gold.dim_products
GROUP BY product_cat
ORDER BY avg_cost DESC

-- what is the total revenue generated for each catergory ?
select
p.product_cat,
SUM(f.sales) as total_revenue
from gold.facts_sales f
left join gold.dim_products p
on     f.product_key = p.product_key
GROUP BY p.product_cat
order by total_revenue DESC

-- find total revenue generated by each customer
select
c.customer_key,
SUM(f.sales) as total_revenue
from gold.facts_sales f
left join gold.dim_customers c
on     f.customer_key = c.customer_key
GROUP BY c.customer_key
order by  total_revenue DESC

-- another way

select
customer_key,
SUM(price) as total_revenue
from gold.facts_sales
GROUP BY customer_key
order by  total_revenue DESC


-- what is the distribution of sold items across countries ?
select
SUM(f.quantity) as sold_items,
c.country
from gold.facts_sales f
LEFT JOIN gold.dim_customers c 
on      f.customer_key = c.customer_key
GROUP BY c.country
order by sold_items DESC
